"""Presentation-only glossary and contextual help for Strategy Builder."""

STRATEGY_BUILDER_HELP_JS = r"""
(() => {
  'use strict';
  if (window.location.pathname !== '/research/strategy') return;

  const HELP = {
    'Historical lookback': ['Historical lookback', 'How far back SCOUT searches for entry signals. It does not change the indicator period or the post-entry holding period.'],
    'Maximum holding period (forced exit)': ['Maximum holding period', 'The latest session on which the current simulation will close a trade if no earlier exit fires. This is a real forced exit, not just a reporting horizon.'],
    'Ranking metric (used only when capped)': ['Ranking metric', 'Used only when more stocks qualify on one day than the daily signal cap allows. It chooses which already-qualified signals are retained; it does not create an entry signal.'],
    'Daily signal cap (500 = current app maximum)': ['Daily signal cap', 'Maximum number of qualifying signals retained per day. At 500, the current reviewed cohort is effectively uncapped.'],
    'Indicator': ['Indicator', 'A market measurement such as a moving average, RSI, MACD, Bollinger Bands, ATR or relative volume. Indicators are building blocks, not complete strategies.'],
    'Condition / output': ['Condition', 'What you want SCOUT to test about the selected indicator, for example price above an SMA or price crossing the Bollinger middle band.'],
    'Comparison': ['Comparison', 'How the measured value is compared with your threshold, such as above, below, at least or at most. Trigger-style conditions do not need a numeric comparison.'],
    'Value': ['Threshold value', 'The numeric level required by the condition. It is hidden when the selected condition is simply true/false, such as a crossover.'],
    'Entry slippage (bps)': ['Entry slippage', 'Modeled price disadvantage when entering. 1 basis point = 0.01%. Five bps means 0.05% worse than the reference entry price.'],
    'Normal exit slippage (bps)': ['Normal exit slippage', 'Modeled price disadvantage on a normal exit. Stop exits can add separate stop slippage on top.'],
    'Additional stop slippage (bps)': ['Additional stop slippage', 'Extra execution penalty applied only when a stop is triggered, intended to reflect gaps and poorer stop fills.'],
    'Commission (bps per side)': ['Commission', 'Explicit commission charged on entry and exit, expressed in basis points per side.'],
    'Entry events': ['Entry events', 'All historical signals generated by the entry definition inside the research window.'],
    'Common complete events': ['Common complete events', 'Signals with enough usable future data for every exit policy in the comparison. Every row uses these same event IDs.'],
    'Exit candidates + hold': ['Exit candidates + hold', 'The number of exit policies compared, including the hold-to-maximum-period control.'],
    'Stop-out': ['Stop-out rate', 'Percentage of complete trades that were closed by the stop before the maximum holding period.'],
    'Expectancy': ['Expectancy', 'Average modeled return per trade across the historical sample after the configured execution costs. It is not annualized portfolio return.'],
    'Delta vs hold': ['Delta vs hold', 'Difference in average return between this exit policy and the hold-to-maximum-period control. Positive means the exit improved average return in this sample; negative means it reduced it.'],
    'Win rate': ['Win rate', 'Percentage of modeled trades with a positive realized return. A high win rate can still coexist with poor expectancy if losses are much larger than wins.'],
    'PF': ['Profit factor', 'Total gains from winning trades divided by the absolute total losses from losing trades. Above 1 means gross gains exceeded gross losses in this sample.'],
    'Payoff': ['Payoff ratio', 'Average winning return divided by the absolute average losing return. Above 1 means the typical winner was larger than the typical loser.'],
    'P05': ['5th-percentile return (P05)', 'A downside-tail measure. Roughly 5% of modeled trade outcomes were worse than this value and 95% were better.'],
    'Avg hold': ['Average holding period', 'Average number of trading sessions the policy kept a position open.'],
    'Median hold': ['Median holding period', 'Half of trades were held for fewer sessions and half for more.'],
    'Median MAE': ['Median MAE', 'Median Maximum Adverse Excursion: the typical worst move against the entry before the simulated exit. More negative means deeper adverse movement.'],
    'Median MFE': ['Median MFE', 'Median Maximum Favorable Excursion: the typical best move above the entry during the full research path, whether or not a stop exited earlier.'],
    'Median drawdown': ['Median drawdown', 'Typical maximum peak-to-trough decline experienced before the simulated exit.'],
    'Gap-through': ['Gap-through frequency', 'Among stopped trades, how often the market opened beyond the stop level so the assumed fill was worse than the stop price.'],
  };

  const INDICATORS = {
    moving_average: ['Moving Average', 'Smooths price over a chosen period. SMA weights each observation equally; EMA gives more weight to recent prices. Common uses include trend direction, support/resistance context and crossovers.'],
    price_roc: ['Price Rate of Change (ROC)', 'Percentage price change over the selected lookback. Positive values mean price rose over that period; negative values mean it fell.'],
    rsi: ['Relative Strength Index (RSI)', 'Momentum oscillator from 0 to 100 comparing recent gains with recent losses. It does not mean relative strength versus another stock or index.'],
    macd: ['MACD', 'Momentum/trend indicator built from the difference between a fast and slow EMA, plus a signal EMA. Crossovers and histogram values describe changes in momentum.'],
    bollinger_bands: ['Bollinger Bands', 'A moving-average center line with upper and lower bands set a chosen number of standard deviations away. Band touches and crossings describe price relative to recent volatility.'],
    atr: ['Average True Range (ATR)', 'Measures typical recent trading range, including overnight gaps. ATR is volatility, not direction.'],
    relative_volume: ['Relative Volume (RVOL)', 'Current volume divided by the average volume over the selected prior period. 1.5x means current volume is 50% above that baseline.'],
    average_dollar_volume: ['Average Dollar Volume', 'Average daily traded dollar value over the selected period, useful as a liquidity measurement.'],
    historical_volatility: ['Historical Volatility', 'Annualized variability of recent close-to-close returns. Higher values mean price has been moving more erratically.'],
    prior_high: ['Price vs Prior High', 'Compares current price with the highest price in the selected prior lookback, excluding the current session from the historical boundary.'],
  };

  let panel = document.getElementById('strategy-help-panel');
  if (!panel) {
    panel = document.createElement('dialog');
    panel.id = 'strategy-help-panel';
    panel.style.cssText = 'max-width:620px;width:min(620px,92vw);border:1px solid #3a4657;border-radius:12px;background:#121720;color:#edf1f7;padding:20px;';
    panel.innerHTML = '<form method="dialog"><button style="float:right">Close</button></form><h2 id="strategy-help-title"></h2><p id="strategy-help-body" style="line-height:1.6"></p><div style="color:#98a6b8;font-size:12px">Help text explains the displayed metric; it does not add analytical evidence.</div>';
    document.body.append(panel);
  }

  function show(title, body) {
    panel.querySelector('#strategy-help-title').textContent = title;
    panel.querySelector('#strategy-help-body').textContent = body;
    if (typeof panel.showModal === 'function') panel.showModal();
  }

  function addHelpToLabel(label) {
    if (!(label instanceof HTMLElement) || label.dataset.helpWired === '1') return;
    const key = [...label.childNodes].find((node) => node.nodeType === Node.TEXT_NODE)?.textContent?.trim();
    const content = HELP[key];
    if (!content) return;
    label.dataset.helpWired = '1';
    const button = document.createElement('button');
    button.type = 'button'; button.textContent = '?'; button.title = `Explain ${content[0]}`;
    button.style.cssText = 'width:22px;height:22px;padding:0;border-radius:50%;display:inline-grid;place-items:center;margin-left:5px;';
    button.addEventListener('click', (event) => { event.preventDefault(); show(content[0], content[1]); });
    label.insertBefore(button, label.querySelector('select,input,textarea,div') || null);
    label.addEventListener('contextmenu', (event) => { event.preventDefault(); show(content[0], content[1]); });
  }

  function addHelpToHeader(header) {
    if (!(header instanceof HTMLElement) || header.dataset.helpWired === '1') return;
    const content = HELP[header.textContent.trim()];
    if (!content) return;
    header.dataset.helpWired = '1'; header.title = `Right-click for: ${content[0]}`;
    header.style.cursor = 'help';
    header.addEventListener('contextmenu', (event) => { event.preventDefault(); show(content[0], content[1]); });
  }

  function wireRule(row) {
    if (!(row instanceof HTMLElement) || row.dataset.helpRuleWired === '1') return;
    row.dataset.helpRuleWired = '1';
    const indicator = row.querySelector('.rule-indicator');
    const metric = row.querySelector('.rule-metric');
    indicator?.addEventListener('contextmenu', (event) => {
      event.preventDefault(); const content = INDICATORS[indicator.value] || ['Indicator', 'Reusable market measurement used by this entry condition.']; show(content[0], content[1]);
    });
    metric?.addEventListener('contextmenu', (event) => {
      event.preventDefault();
      const selected = metric.options[metric.selectedIndex]?.textContent || 'Condition';
      const indicatorContent = INDICATORS[indicator?.value];
      show(selected, indicatorContent ? `${selected} is a condition derived from ${indicatorContent[0]}. ${indicatorContent[1]}` : 'This is the selected condition produced by the indicator.');
    });
    indicator.title = 'Right-click for a plain-English explanation of the selected indicator.';
    metric.title = 'Right-click for a plain-English explanation of the selected condition.';
  }

  function wireAll() {
    document.querySelectorAll('label').forEach(addHelpToLabel);
    document.querySelectorAll('th,.metric-label').forEach(addHelpToHeader);
    document.querySelectorAll('.rule-row').forEach(wireRule);
  }
  wireAll();
  new MutationObserver(wireAll).observe(document.body, {childList: true, subtree: true});
})();
"""

__all__ = ["STRATEGY_BUILDER_HELP_JS"]
