# ruff: noqa: E501
"""Self-hosted browser asset for the local Strategy Builder composer."""

STRATEGY_BUILDER_JS = r"""
(()=>{'use strict';const $=id=>document.getElementById(id),form=$('strategy-form');if(!form)return;
const catalog=JSON.parse($('strategy-catalog-json').textContent||'[]'),rules0=JSON.parse($('initial-rules-json').textContent||'[]'),stops0=JSON.parse($('initial-stops-json').textContent||'[]'),rules=$('rule-rows'),stops=$('stop-rows');
const groups=new Map(),inds=[];for(const m of catalog){if(!groups.has(m.indicator_id)){groups.set(m.indicator_id,[]);inds.push([m.indicator_id,m.indicator_label]);}groups.get(m.indicator_id).push(m)}
const opt=(v,t,s=false)=>{const o=document.createElement('option');o.value=v;o.textContent=t;o.selected=s;return o},metric=f=>catalog.find(x=>x.feature_name===f)||catalog[0];
function ruleRow(r=null){const m=metric(r?.feature_name),d=document.createElement('div');d.className='composer-row rule-row';d.innerHTML='<label>Join<select class="rj"><option value="and">AND</option><option value="or">OR</option></select></label><label>Indicator<select class="ri"></select></label><label>Metric / trigger<select class="rm"></select></label><label>Relationship<select class="ro"><option>&gt;</option><option>&gt;=</option><option>&lt;</option><option>&lt;=</option><option>==</option><option>!=</option></select></label><label>Threshold<input class="rv" type="number"></label><label class="slider-wrap">Fine control<input class="rs" type="range"></label><button class="remove-row" type="button">Remove</button><div class="rule-meta"></div>';
const I=d.querySelector('.ri'),M=d.querySelector('.rm'),O=d.querySelector('.ro'),V=d.querySelector('.rv'),S=d.querySelector('.rs'),J=d.querySelector('.rj'),meta=d.querySelector('.rule-meta');for(const [id,label] of inds)I.append(opt(id,label,id===m.indicator_id));
function fill(feature=null){const ms=groups.get(I.value)||[];M.replaceChildren(...ms.map(x=>opt(x.feature_name,x.metric_label,x.feature_name===feature)));if(!ms.some(x=>x.feature_name===feature)&&ms[0])M.value=ms[0].feature_name;defaults(feature===null)}
function defaults(force=true){const x=metric(M.value);V.min=x.min_value;V.max=x.max_value;V.step=x.step;S.min=x.min_value;S.max=x.max_value;S.step=x.step;if(force){O.value=x.default_operator;V.value=x.default_value}S.value=V.value;meta.textContent=`${x.parameter_summary} · ${x.unit_label} · ${x.description}`}
I.onchange=()=>fill(null);M.onchange=()=>defaults(true);V.oninput=()=>S.value=V.value;S.oninput=()=>V.value=S.value;d.querySelector('.remove-row').onclick=()=>{d.remove();first()};fill(r?.feature_name||null);if(r){O.value=r.operator;V.value=r.value;S.value=r.value;J.value=r.join||'and'}return d}
function first(){[...rules.children].forEach((d,i)=>{const j=d.querySelector('.rj');j.disabled=i===0;if(i===0)j.value='and'})}function addRule(r=null){rules.append(ruleRow(r));first()}
const bounds=f=>(f==='fixed'||f==='trailing')?{min:.01,max:99.99,step:.01,unit:'%'}:{min:.01,max:20,step:.01,unit:'x ATR'};
function stopRow(s=null){const d=document.createElement('div');d.className='composer-row stop-row';d.innerHTML='<label>Exit type<select class="sf"><option value="fixed">Fixed % stop</option><option value="trailing">Trailing % stop</option><option value="atr">ATR stop</option><option value="trailing_atr">Trailing ATR stop</option></select></label><label>Exact value<input class="sv" type="number"></label><label class="slider-wrap">Slider<input class="ss" type="range"></label><div class="stop-unit"></div><button class="remove-row" type="button">Remove</button>';const F=d.querySelector('.sf'),V=d.querySelector('.sv'),S=d.querySelector('.ss'),U=d.querySelector('.stop-unit');F.value=s?.family||'fixed';V.value=s?.value||5;function b(){const x=bounds(F.value);Object.assign(V,{min:x.min,max:x.max,step:x.step});Object.assign(S,{min:x.min,max:x.max,step:x.step});let n=Number(V.value);if(!Number.isFinite(n)||n<x.min||n>x.max)n=F.value.includes('atr')?2:5;V.value=n;S.value=n;U.textContent=`${x.unit} · ${x.min} to ${x.max}`}F.onchange=b;V.oninput=()=>S.value=V.value;S.oninput=()=>V.value=S.value;d.querySelector('.remove-row').onclick=()=>d.remove();b();return d}
const hidden=(n,v)=>{const i=document.createElement('input');i.type='hidden';i.name=n;i.value=v;i.dataset.gen='1';form.append(i)};$('add-rule').onclick=()=>addRule();$('add-stop').onclick=()=>stops.append(stopRow());$('clear-stops').onclick=()=>stops.replaceChildren();
form.onsubmit=e=>{form.querySelectorAll('[data-gen="1"]').forEach(x=>x.remove());try{if($('entry-mode-visual').checked){const a=[...rules.children].map((d,i)=>({feature:d.querySelector('.rm').value,op:d.querySelector('.ro').value,value:Number(d.querySelector('.rv').value),join:i?' '+d.querySelector('.rj').value+' ':' and '}));if(!a.length||a.some(x=>!Number.isFinite(x.value)))throw Error('Every visual rule needs a finite threshold.');let ex=`${a[0].feature} ${a[0].op} ${a[0].value}`;a.slice(1).forEach(x=>ex=`(${ex}${x.join}${x.feature} ${x.op} ${x.value})`);hidden('expression',ex);a.forEach((x,i)=>{hidden('rule_feature',x.feature);hidden('rule_operator',x.op);hidden('rule_value',String(x.value));hidden('rule_join',i?' '+x.join.trim()+' ':'and')})}else{const ex=$('advanced-expression').value.trim();if(!ex)throw Error('Advanced expression cannot be empty.');hidden('expression',ex)}const g={fixed:[],trailing:[],atr:[],trailing_atr:[]};for(const d of stops.children){const f=d.querySelector('.sf').value,v=Number(d.querySelector('.sv').value),x=bounds(f);if(!Number.isFinite(v)||v<x.min||v>x.max)throw Error(`Exit value must be ${x.min} to ${x.max}.`);g[f].push(v)}hidden('fixed_stops',g.fixed.join(','));hidden('trailing_stops',g.trailing.join(','));hidden('atr_stops',g.atr.join(','));hidden('trailing_atr',g.trailing_atr.join(','))}catch(err){e.preventDefault();$('composer-error').hidden=false;$('composer-error').textContent=err.message||String(err)}};
rules0.length?rules0.forEach(addRule):addRule({feature_name:'return_20',operator:'>=',value:.05,join:'and'});stops0.forEach(s=>stops.append(stopRow(s)));function mode(){ $('visual-builder-panel').hidden=!$('entry-mode-visual').checked;$('advanced-builder-panel').hidden=!$('entry-mode-advanced').checked}$('entry-mode-visual').onchange=mode;$('entry-mode-advanced').onchange=mode;mode();})();
"""

__all__ = ["STRATEGY_BUILDER_JS"]
