"""Batch and incremental consolidation-event generation through PatternState lifecycle.

This module composes the persistent consolidation tracker with the discrete event layer. Pattern
geometry remains upstream, event confirmation remains here, and both historical replay and
incremental scanning use the same update path.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from trade_scout.data.contracts import CorporateActionRecord, ResearchBar
from trade_scout.events.consolidation_breakout import (
    ConsolidationBreakoutEvent,
    event_from_pattern_state,
)
from trade_scout.patterns import (
    ConsolidationLifecycleConfig,
    ConsolidationPatternTracker,
    PatternLifecycleState,
    PatternState,
)
from trade_scout.patterns.consolidation_breakout import ConsolidationBreakoutConfig


@dataclass(frozen=True, slots=True)
class ConsolidationEventConfig:
    """Event-side confirmation and deduplication settings."""

    cooldown_sessions: int = 5
    min_breakout_volume_ratio: float | None = None
    volume_lookback_sessions: int = 20

    def __post_init__(self) -> None:
        if not 0 <= self.cooldown_sessions <= 252:
            raise ValueError("cooldown_sessions must be between 0 and 252")
        if self.min_breakout_volume_ratio is not None and self.min_breakout_volume_ratio <= 0:
            raise ValueError("min_breakout_volume_ratio must be positive when supplied")
        if not 2 <= self.volume_lookback_sessions <= 252:
            raise ValueError("volume_lookback_sessions must be between 2 and 252")

    @classmethod
    def from_legacy_config(cls, config: ConsolidationBreakoutConfig) -> ConsolidationEventConfig:
        """Preserve current exploratory event semantics during migration."""

        return cls(
            cooldown_sessions=config.cooldown_sessions,
            min_breakout_volume_ratio=config.min_breakout_volume_ratio,
            volume_lookback_sessions=config.volume_lookback_sessions,
        )


@dataclass(frozen=True, slots=True)
class ConsolidationPipelineUpdate:
    """Point-in-time output generated by one incremental session update."""

    pattern_states: tuple[PatternState, ...]
    event: ConsolidationBreakoutEvent | None


@dataclass(frozen=True, slots=True)
class ConsolidationPipelineReplay:
    """Deterministic batch replay assembled from the incremental update path."""

    pattern_states: tuple[PatternState, ...]
    events: tuple[ConsolidationBreakoutEvent, ...]


class IncrementalConsolidationPipeline:
    """Single-session consolidation pipeline shared by replay and later scanning."""

    def __init__(
        self,
        pattern_config: ConsolidationBreakoutConfig,
        *,
        event_config: ConsolidationEventConfig | None = None,
        lifecycle_config: ConsolidationLifecycleConfig | None = None,
    ) -> None:
        self.pattern_config = pattern_config
        self.event_config = event_config or ConsolidationEventConfig.from_legacy_config(
            pattern_config
        )
        resolved_lifecycle = lifecycle_config or ConsolidationLifecycleConfig(
            reset_sessions=self.event_config.cooldown_sessions
        )
        self.lifecycle_config = resolved_lifecycle
        self._tracker = ConsolidationPatternTracker(pattern_config, resolved_lifecycle)
        self._signal_index = -1
        self._last_event_index = -10_000

    def update(
        self,
        bar: ResearchBar,
        *,
        corporate_actions: tuple[CorporateActionRecord, ...] = (),
    ) -> ConsolidationPipelineUpdate:
        """Advance one bar using only information available through that bar."""

        self._signal_index += 1
        pattern = self._tracker.update(bar, corporate_actions=corporate_actions)
        if pattern is None:
            return ConsolidationPipelineUpdate(pattern_states=(), event=None)

        states = [pattern]
        if pattern.state not in {
            PatternLifecycleState.QUALIFIED,
            PatternLifecycleState.TRIGGER_READY,
        }:
            return ConsolidationPipelineUpdate(pattern_states=tuple(states), event=None)
        if self._signal_index - self._last_event_index <= self.event_config.cooldown_sessions:
            return ConsolidationPipelineUpdate(pattern_states=tuple(states), event=None)
        if not _volume_confirmed(
            self._tracker.bars,
            signal_index=self._signal_index,
            config=self.event_config,
        ):
            return ConsolidationPipelineUpdate(pattern_states=tuple(states), event=None)

        event = event_from_pattern_state(pattern, bar, signal_index=self._signal_index)
        if event is None:
            return ConsolidationPipelineUpdate(pattern_states=tuple(states), event=None)

        states.append(self._tracker.consume(bar))
        self._last_event_index = self._signal_index
        return ConsolidationPipelineUpdate(pattern_states=tuple(states), event=event)


def replay_consolidation_pipeline(
    bars: tuple[ResearchBar, ...],
    pattern_config: ConsolidationBreakoutConfig,
    *,
    event_config: ConsolidationEventConfig | None = None,
    lifecycle_config: ConsolidationLifecycleConfig | None = None,
    corporate_actions: tuple[CorporateActionRecord, ...] = (),
) -> ConsolidationPipelineReplay:
    """Reconstruct historical states/events by feeding the incremental engine in date order."""

    if not bars:
        raise ValueError("at least one research bar is required")
    actions_by_date: dict[date, list[CorporateActionRecord]] = {}
    for action in corporate_actions:
        actions_by_date.setdefault(action.effective_date, []).append(action)

    engine = IncrementalConsolidationPipeline(
        pattern_config,
        event_config=event_config,
        lifecycle_config=lifecycle_config,
    )
    states: list[PatternState] = []
    events: list[ConsolidationBreakoutEvent] = []
    for bar in bars:
        update = engine.update(
            bar,
            corporate_actions=tuple(actions_by_date.get(bar.trade_date, ())),
        )
        states.extend(update.pattern_states)
        if update.event is not None:
            events.append(update.event)
    return ConsolidationPipelineReplay(pattern_states=tuple(states), events=tuple(events))


def detect_consolidation_events(
    bars: tuple[ResearchBar, ...],
    pattern_config: ConsolidationBreakoutConfig,
    *,
    event_config: ConsolidationEventConfig | None = None,
    lifecycle_config: ConsolidationLifecycleConfig | None = None,
    corporate_actions: tuple[CorporateActionRecord, ...] = (),
) -> tuple[ConsolidationBreakoutEvent, ...]:
    """Generate breakout events through the shared persistent lifecycle pipeline."""

    return replay_consolidation_pipeline(
        bars,
        pattern_config,
        event_config=event_config,
        lifecycle_config=lifecycle_config,
        corporate_actions=corporate_actions,
    ).events


def _volume_confirmed(
    bars: tuple[ResearchBar, ...],
    *,
    signal_index: int,
    config: ConsolidationEventConfig,
) -> bool:
    threshold = config.min_breakout_volume_ratio
    if threshold is None:
        return True
    if signal_index < config.volume_lookback_sessions:
        return False
    trailing = bars[signal_index - config.volume_lookback_sessions : signal_index]
    if any(item.volume < 0 for item in trailing) or bars[signal_index].volume < 0:
        return False
    average = sum(item.volume for item in trailing) / config.volume_lookback_sessions
    if average <= 0:
        return False
    return bars[signal_index].volume / average >= threshold
